server:
  port: 8003
spring:
  application:
    name: manage-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      routes:
        - id: manage-admin
        uri: lb://MANAGE-ADMIN
        # predicates:
        #  - Path=/test/**
        filters:
          - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
